apiVersion: v1
appVersion: amd64-7260c12f-ls33
description: couchpotato is a movie downloading client
name: couchpotato
version: 1.0.0
keywords:
  - couchpotato
  - usenet
  - bittorrent
home: https://github.com/billimek/billimek-charts/tree/master/charts/couchpotato
icon: https://github.com/CouchPotato/CouchPotatoServer/raw/master/couchpotato/static/images/icons/android.png
sources:
  - https://hub.docker.com/r/linuxserver/couchpotato/
  - https://github.com/CouchPotato/CouchPotatoServer/
maintainers:
  - name: skaro13
    email: simon.caron@protonmail.com
