
{{- if and .Values.persistence.source.enabled (not .Values.persistence.source.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "duplicati.fullname" . }}-source
  {{- if .Values.persistence.source.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "duplicati.name" . }}
    helm.sh/chart: {{ include "duplicati.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.source.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.source.size | quote }}
{{- if .Values.persistence.source.storageClass }}
{{- if (eq "-" .Values.persistence.source.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.source.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}